DjangoCRUD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
app_name = 'guestbook'
urlpatterns = [
    url(r'^guestbook/',include(('guestbook.urls','guestbook'), namespace='guestbook')),
    url(r'^admin/', admin.site.urls),
]

guestbook/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.list, name ='list'),
    url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
    url(r'^update/(?P<update_id>[0-9]+)$', views.update, name='update'),
    url(r'^create/$', views.create, name = 'create'),

]

guestbook/models.py
from django.db import models

# Create your models here.
class guestbook(models.Model):
    nama = models.CharField(max_length=50)
    alamat = models.CharField(max_length=50)
    email = models.CharField(max_length=50)

    def __str__(self):
        return "{}.{}".format(self.id, self.email)

guestbook/forms.py
from django import forms
from .models import guestbook

class guestbookForm(forms.ModelForm):
    class Meta:
      model = guestbook
      fields = [
         'nama',
         'alamat',
         'email',
        ]

guestbook/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import guestbook
from .forms import guestbookForm

def create(request):
    akun_form = guestbookForm(request.POST or None)

    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()
        return redirect('guestbook:list')    

    context = {
        "page_title":"Tambah akun",
        "akun_form": akun_form,
    }

    return render(request, 'guestbook/create.html', context)

def home(request):
    return render(request,'index.html')

def list(request):
    semua_guest = guestbook.objects.all()

    context = {
        'page_title':'Guest Boook',
        'semua_guest': semua_guest,
    }
    return render(request,'guestbook/list.html', context)

def delete(request, delete_id):
    guestbook.objects.filter(id=delete_id).delete()
    return redirect('guestbook:list')

def update(request, update_id):
    akun_update = guestbook.objects.get(id=update_id)
    data = {
        'nama'  : akun_update.nama,
        'alamat': akun_update.alamat,
        'email' : akun_update.email,
    }
    akun_form = guestbookForm(request.POST or None, initial=data, instance=akun_update)

    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()
        return redirect('guestbook:list')    

    context = {
        "page_title":"Tambah akun",
        "akun_form": akun_form,
    }

    return render(request, 'guestbook/create.html', context)

guestbook/templates/guestbook/create.html
{% extends 'base.html' %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block contents %}
    <form method="POST">
        {% csrf_token %}
        <table>
            {{akun_form.as_table}}
        </table>
        <button type="Submit">Kirim</button>
    </form>    
{% endblock contents %}

guestbook/templates/guestbook/list.html
{% extends 'base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{page_title}}</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama</th>
      <th scope="col">Alamat</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>

    {% for akun in semua_guest  %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{akun.nama}}</td>
        <td>{{akun.alamat}}</td>
        <td>{{akun.email}}</td>
        <td><a class="btn btn-danger" href="{% url 'guestbook:delete' akun.id %}">Delete</a></td>
        <td><a class="btn btn-warning" href="{% url 'guestbook:update' akun.id %}">Update</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-primary"href="{% url 'guestbook:create' %}">Add</a>
{% endblock contents %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>
        {% block title %}

        {% endblock title %}
    </title>
  </head>
  <body>
    <div class="continer">
    {% block contents %}
    
    {% endblock contents %}
    </div> 

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html> 

templates/index.html
{% extends 'base.html' %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block contents %}
  <h1>{{page_title}}</h1>
{% endblock contents %}